# Generated by Django 6.0.3 on 2026-03-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('key_generate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='key',
            name='key_code',
            field=models.CharField(unique=True),
        ),
    ]
